# Generated by Django 6.0.6 on 2026-06-13 14:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_qr_code_booking_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='security_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
