version: '3.8'

services:
  # 1. Frontend: NGINX + React Static Build
  frontend:
    build:
      context: ./frontend
    container_name: cineverse_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  # 2. Redis: Cache & Celery Message Broker
  redis:
    image: redis:alpine
    container_name: cineverse_redis
    ports:
      - "6379:6379"

  # 3. Backend: Gunicorn + Django
  backend:
    build:
      context: ./backend
    container_name: cineverse_backend
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  # 4. Celery Worker (Background Tasks)
  celery-worker:
    build:
      context: ./backend
    container_name: cineverse_celery_worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - backend
    command: celery -A cineverse_backend worker -l INFO

  # 5. Celery Beat (Scheduler)
  celery-beat:
    build:
      context: ./backend
    container_name: cineverse_celery_beat
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - backend
    command: celery -A cineverse_backend beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
