# Generated by Django 6.0.6 on 2026-06-13 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('duration_minutes', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('rating', models.CharField(help_text='e.g., PG-13, R', max_length=10)),
                ('genre', models.CharField(max_length=100)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('poster_image', models.URLField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, help_text='Comma separated cast members', null=True)),
                ('moods', models.CharField(blank=True, help_text='Comma separated moods, e.g., Happy, Excited', max_length=255)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_upcoming', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
            ],
        ),
    ]
